### PR TITLE
Rename task and queue

### PR DESCRIPTION
**Pull request by mheguy**
This can either be a step towards https://github.com/Refactorio/RedMew/issues/452 or close it fully if people find the names acceptable as long-term replacements. I personally don't like `processing_queue` and would want to change that back after 3-4 weeks when the change propagates to all (or most) forks.

### CODE REVIEW

**Comment by mheguy** [comment]
After a quick look at current open PRs, this should not create issues with any.

**Review by linaori — APPROVED** [review]
This is a nice solution, I like it!

You're not actually threading anything, it's more like scheduling, but it feels like threading so I'm giving it a 👍  anyway

**Comment by Valansch** [comment]
This used to be calles threading. :D We renamed it task as that was uhm more approriate? Task isnt good either, but its certainly not threading either. How about "async" or like lin proposed "scheduling".

**Review by linaori — APPROVED** [review]

**Comment by grilledham** [comment]
I don't approve of renaming Queue to processing_queue, Queue is just a standard FIFO data structure. It has nothing to do with the scheduler, it just happens to be part of its implementation.
We should rename it to lower case however to be consistent.

**Comment by linaori** [comment]
@grilledham that causes issues on windows

**Comment by mheguy** [comment]
> We should rename it to lower case however to be consistent.

@grilledham @iltar that causes issues on linux as well. I detailed that in https://github.com/Refactorio/RedMew/issues/452#issuecomment-442008290 but as a tl;dr: unless set up to do otherwise, git will not rename files just for case. We just can't go from A to B. We need some kind of middle step.

What I was planning on doing originally with both `Task` and `Queue` was just renaming from from singular to plural forms. Would that be acceptable? To rename `Queue` to `queues` for a few weeks then change it to `queue` afterwards?

**Comment by mheguy** [comment]
image

**Comment by Valansch** [comment]
q... ffs. Well played.

**Pull request merged**
