### PR TITLE
Turkey.lua Improvements

### PR DESCRIPTION
**Pull request by Zahir-Khan**
Removed vanilla ore spawn.

### CODE REVIEW

**Comment by grilledham** [comment]
Line 150 could use `Event.on_nth_tick`

**Comment by Zahir-Khan** [comment]
> Line 150 could use `Event.on_nth_tick`

There was a mention of desync possibility, that is why I didn't use it and also I don't quite understand it fully.

**Comment by grilledham** [comment]
We use it a lot, so there shouldn't be any desync risk.

Something like this should work:
```lua
Event.on_nth_tick(36000,
    function(event)
            local message = turkey_message_random[math.random(#turkey_message_random)]
            game.print('[color=yellow][font=compi]' .. message .. '[/font][/color]')
    end
)
```

**Comment by Zahir-Khan** [comment]
This closes #1013

**Pull request merged**
