### PR TITLE
Quadrants balance update

### PR DESCRIPTION
**Pull request by SimonFlapse**
Tweaked hail hydra to prevent worms from spawning from spitter. This would cause the worms to sometimes spawn outside a turrets range, thus destroying all defences.

Added mapgen settings based on feedback

Added rendering.draw_text for markets to help new comers understand what/where the market is
Included a en, de and da translation of the market name:

Showing danish translation:
image
Says:
English: Market
German: Markt

### CODE REVIEW

**Comment by linaori** [comment]
Can we make rendering of those names a toggle? :smile: Perhaps via settings?

**Comment by SimonFlapse** [comment]
You can, rendering texts have a render_to table

**Comment by mheguy** [comment]
Quadrants is all yours. Merge at your convenience.

**Comment by mheguy** [comment]
If you want to cut a file out, you can combine `map_settings.lua` and `mapgen_settings.lua`, either returning 2 tables or returning a table containing the 2 tables.

**Comment by plague006** [comment]
Closing without prejudice. Feel free to re-open any time you want to merge. I'm simply closing this to take it off the list of open PRs and because I don't know the scenario well enough to feel comfortable merging it. :)

**Pull request merged**
