### PR TITLE
Fixing for 0.17.35

### PR DESCRIPTION
**Pull request by SimonFlapse**
Fixes based on: https://forums.factorio.com/70188 for 0.17.35 release

### CODE REVIEW

**Comment by SimonFlapse** [comment]
I think I've gotten all of them. I have yet to test it. The ones in Quadrant have been fixed in #863 
@plague006 Travis needs to have his defines updated to reflect the renaming of player inventories

**Comment by grilledham** [comment]
I'm going to merge this now so it updates the scenarios on the server. If we find more problems we can make a new PR.

**Comment by mheguy** [comment]
I opened https://github.com/Refactorio/RedMew/issues/904 for changes to luacheckrc based on https://github.com/Refactorio/RedMew/pull/902#issue-275397758, but it seems like grilled got to it? Are there any outstanding changes to be made?

**Comment by SimonFlapse** [comment]
Not that I know of

**Pull request merged**
