### PR TITLE
Score GUI - Converted to rich text

### PR DESCRIPTION
**Pull request by SimonFlapse**
- Reducing the footprint

Tooltip on mouse over:
image

I'm not sure how it'll look when you reach multi-digit numbers

### CODE REVIEW

**Comment by grilledham** [comment]
This looks good 👍 

I would like to know how it looks when the numbers are filled out, does it become too long?

Also is there an advantage to using rich text over sprites. If we used sprites we could avoid the concat.

**Comment by SimonFlapse** [comment]
Performance wise I don't know. But I think it's easier to implement it using the new image tag since it's just a string. Nothing is stopping us from just doing sprites

**Comment by SimonFlapse** [comment]
image
UI Scaling handles this well.

**Comment by mheguy** [comment]
Looks good to me, merging with my thanks.

**Comment by mheguy** [comment]
Taking a second look at it, the hand icon is pretty vague. Would hand + assembler be more clear? Similarly the robot makes it seem like that's a bot count.

**Pull request merged**
