### PR TITLE
Added groundhogs, updated dino_island

### PR DESCRIPTION
**Pull request by SimonFlapse**
Needs #723 
Plague edit: closes https://github.com/Refactorio/RedMew/pull/722

### CODE REVIEW

**Comment by plague006** [comment]
Actually, this will close #723. :D

**Comment by mheguy** [comment]
FP to catch up to dev

**Comment by grilledham** [comment]
Maybe dino_islands with groundhogs should be a separate map, rather than changing dino_islands.

**Comment by SimonFlapse** [comment]
Since dino_island needed to be updated anyways, I just added a boolean value to enable groundhogs. We can split them up if you'd still want that, when #723 has been merged

**Comment by mheguy** [comment]
FP to get #723 in. 
The integration of `RestrictEntities` looks good to me.

**Comment by SimonFlapse** [comment]
I've added a "toggle" for groundhogs. Minor testing, LGTM

**Comment by mheguy** [comment]
I think the only changes remaining that aren't covered by the toggle are hail hydra, disabling loaders, and the tweaks to the ore numbers. I'll leave that for @grilledham to decide how to proceed.

**Comment by grilledham** [comment]
I don't think we really have a good solution for toggles in presets available currently, so I'm willing to accept this as is.

**Pull request merged**
