### PR TITLE
Fixed a little translation into Russian.

### PR DESCRIPTION
**Pull request by click0**
Subj.

### CODE REVIEW

**Comment by click0** [comment]
@Ku3mi41 надо объединить наши правки, а то будет двойная работа.

**Comment by mheguy** [comment]
#888 created conflicts with this PR that need to be resolved.

**Comment by click0** [comment]
Like, fixed commits.

**Comment by mheguy** [comment]
Merge conflicts still need to resolved by author.

**Comment by click0** [comment]
There are no conflicts on my side.
Understand yourself with travis-ci settings.

**Comment by mheguy** [comment]
I assure you, the conflicts are on your side and are fully unrelated to travis.
image

**Comment by click0** [comment]
I assure you, the problem is on your side.

On my local repository, commits without errors merged.
изображение


I also took github on my side without any problems, you can see for yourself. 
https://github.com/click0/RedMew/commits/develop

Now I see this non-informative message from travis-ci.
изображение


Therefore, I see that the problem is in the settings of travis-ci.

**Comment by mheguy** [comment]
Rather than https://github.com/click0/RedMew/commits/develop which is just a meaningless list of commits check https://github.com/Refactorio/RedMew/compare/develop...click0:develop which shows how your branch will merge with our codebase.

See the red `x` at the top?
image

That is because there are merge conflicts.

If you want the information outside of github and travis' reach entirely, here's what it looks like from CLI git:

image

**Comment by mheguy** [comment]
As I mentioned several comments above (https://github.com/Refactorio/RedMew/pull/891#issuecomment-480627671) these merge conflicts arose from #888 because both PRs wanted to modify the same files.

It doesn't indicate a fault with either author, just a conflict which needs to be resolved. If you're not sure how to address the merge conflicts: just ask rather than deny their very clear existence.

**Comment by click0** [comment]
It seems that everything is ok.

**Pull request merged**
