### PR TITLE
Added particles when a biter mines a rock upon spawning

### PR DESCRIPTION
**Pull request by linaori**
- Added particles when breaking up rocks, with diminishing amounts for stacked rocks
 - Documented more cheats
 - Added more cheats

Particle effect + hydra mode can be seen here: https://www.youtube.com/watch?v=rSQ3_GkEvRA

### CODE REVIEW

**Comment by SimonFlapse** [comment]
I like the particles. I'll experiment with it and see if I can use it in the force control system. How is performance with it? Is it affected by graphics settings? Could it cause performance issues for low end PC players?

**Comment by linaori** [comment]
I believe there's a setting to hide the particles, but I'm not sure. Testing showed that there was performance overhead, but not even close to spilling about 200 stone.

**Review by Valansch — APPROVED** [review]
Cood is good, i like the look of the 'animation' :)

**Review by mheguy — APPROVED** [review]
Tested and works well. Looks cool.

**Pull request merged**
