### PR TITLE
Add plague's colors

### PR DESCRIPTION
**Pull request by plague006**
Pure vanity..

### CODE REVIEW

**Comment by Valansch** [comment]
I'd rather not have anything player specific in the codebase. Instead of this we could just save all players colors. This should be easily doable on the diffie server. Not so much on the prime server.

**Comment by plague006** [comment]
That's cool, just saw grilled's color and followed suit.

**Comment by Valansch** [comment]
Didnt see that. Sneaky :D

**Comment by Valansch** [comment]
Cant blame you then, so i may as well merge it.

**Comment by plague006** [comment]
Would/could happily split it out into its own resources file so that it's not edits to control.lua if others want to add their own colours.

**Comment by theorangeangle** [comment]
Possible patreon perk?

(Assuming we can get someone to donate on patreon first)

**Comment by plague006** [comment]
Opened https://github.com/Valansch/RedMew/issues/195 to follow up.

**Pull request merged**
