### PR TITLE
Customizable tag message

### PR DESCRIPTION
**Pull request by Quadrum1**
Users can create their own messages for player tags

These messages appear once a player joins or leaves a team

**Still a bug: Can't clear tag once assigned! .**

### CODE REVIEW

**Comment by SimonFlapse** [comment]
You can't clear tags because the player.tag (old_tag) value has brackets in it.
eg. `[Cat]` instead of the expected `Cat`
You cannot change this, but you could do:
```lua
old_tag = string.sub(old_tag, 2, string.len(old_tag)-1)
local tag_data = tag_groups[old_tag]
```
on line 56, and move the other tag_data back to line 66

**Comment by Quadrum1** [comment]
Just noticed that it IS clearing the tag, just not telling it in chat or removing one from the tag window

**Comment by mheguy** [comment]
Tagging this with 0.17 because we're branching at this point to work on 0.17 integration and won't be merging non-fixes until after that is done. Feel free to keep working on this though and we'll absolutely have a look when things have stabilized. :)

**Comment by theorangeangle** [comment]
@Quadrum1 still interested in this? Now that things have stabilized a bit we might be able to look at it.

**Comment by grilledham** [comment]
#958 supersede this. Sorry I didn't spot this PR when I made #958

**Pull request closed without merging**
