### PR TITLE
left align rank cells

### PR DESCRIPTION
**Pull request by grilledham**
I would like to test this with multiple people to confirm that this change does look better.

### CODE REVIEW

**Comment by mheguy** [comment]
You're a monster for not including screenshots. :p

**Comment by mheguy** [comment]
Before
image

After:
image

**Comment by mheguy** [comment]
I believe "Regular (D)" would be the longest possible string in that column. So we could trim the width if that seems appropriate.

Can we also have a popup for it like deaths has that reveals that it is a donator tag?

**Comment by grilledham** [comment]
The longest possible string is `Auto Trusted (D)` I set the column width for that case.

**Comment by mheguy** [comment]
I will always forget that bastard rank. lol

**Pull request merged**
