### PR TITLE
Update info.lua

### PR DESCRIPTION
**Pull request by Claude477**
Changed domain name because old giving SSL errors.
https://cdn.discordapp.com/attachments/432568711698710540/733598102077833236/unknown.png

### CODE REVIEW

**Comment by grilledham** [comment]
map_gen/maps/diggy/feature/cutscene.lua has two instances of www.redmew.com. Can you changes those too.

**Comment by grilledham** [comment]
Sorry I was mistaken, the other instance of www.redmew.com is in map_gen/maps/crashsite/cutscene.lua. Can you change that too. 😄

**Comment by Claude477** [comment]
yup

**Comment by grilledham** [comment]
LGTM thanks 👍

**Pull request merged**
