### PR TITLE
Add DO:X Cross map

### PR DESCRIPTION
**Pull request by RedRafe**
Adds a X Cross map (very similar to the 3Way T shaped one).
Each arm has a main ore among iron, copper, coal, stone.
Map is rotated 45 degrees

x_cross
x_cross_zoom

### CODE REVIEW

**Comment by RedRafe** [comment]
For reference, `main_ores_builder` is same of the 3-way (T cross) just without the tip of one arm cropped, and rotated 45 degs. Same for the scenario code, while ore config is default ore config, + stone not commented out

**Comment by grilledham** [comment]
I don't think the map gen is working, I just get this:
image

I don't get any errors in Debug mode. Do you know what is going on?

**Comment by grilledham** [comment]
My bad, I messed up the require in my map selection.

**Review by grilledham — APPROVED** [review]
Looks good. Stone might be a little high but we can adjust after a playthrough.

**Pull request merged**
