### PR TITLE
diggy hail_hydra patch

### PR DESCRIPTION
**Pull request by Claude477**
this fix some errors

### CODE REVIEW

**Review by SimonFlapse — COMMENTED** [review]
Wouldn't it be better to merge this into #1032? Since it depends upon it.

**Comment by Claude477** [comment]
Yes is true but #1032 has 3 critical files need patch frist then this hail_hydra file. this meybe can changed if not working corretly. plus this need tests out.

**Comment by Claude477** [comment]
S9-server has diggy2020_patch3-deflated.zip if want checkout how is works out.

**Comment by BlueRock2** [comment]
Did some solo testing by setting debug and cheat mode to true, set evolution to 100%, ran /c game.player.force.research_all_technologies()  so that I get the weapon damage upgrades.    Verified blood explosions occurring on alien death (a little larger than the normal blood spray when doing damage that doesn't cause death)  Also verified new aliens randomly spawn on death as expected with hail hydra.

**Comment by BlueRock2** [comment]
After I tested this update, Claude477 indicated ok to merge this update in with PR 1032 which I did this morning.  This PR can be cancelled/closed.

**Pull request closed without merging**
