### PR TITLE
Quick evo fix

### PR DESCRIPTION
**Pull request by SimonFlapse**

### CODE REVIEW

**Comment by SimonFlapse** [comment]
Apparently not working -> Bug in force_control?

**Comment by linaori** [comment]
I found the issue, it's the wrong force 😅 

image

Apply this diff:
```diff
diff --git a/map_gen/Diggy/Feature/Experience.lua b/map_gen/Diggy/Feature/Experience.lua
index 3820ad5..084ec21 100644
--- a/map_gen/Diggy/Feature/Experience.lua
+++ b/map_gen/Diggy/Feature/Experience.lua
@@ -502,6 +502,14 @@ function Experience.register(cfg)
     --Adds the function on how to calculate level caps (When to level up)
     local ForceControlBuilder = ForceControl.register(level_up_formula)

+    local function evolution_boost()
+        game.forces.enemy.evolution_factor = game.forces.enemy.evolution_factor + 0.012
+    end
+
+    for i = 1, 10 do
+        ForceControlBuilder.register_on_single_level(i, evolution_boost)
+    end
+
     --Adds a function that'll be executed at every level up
     ForceControlBuilder.register_on_every_level(function (level_reached, force)
         force.print(string_format('%s Leveled up to %d!', '## - ', level_reached))
```

**Review by Valansch — CHANGES_REQUESTED** [review]
See @iltar s comment

**Comment by SimonFlapse** [comment]
Outdated changes, no longer relevant

**Pull request closed without merging**
