### PR TITLE
Change CI from travis to GitHub Actions, change nightly releases to monthly

### PR DESCRIPTION
**Pull request by mheguy**
This PR involves some backend changes that won't be reflected in the commits (see images).

Travis will no longer handle CI, the webhook from github to travis has been severed, and travis should no longer build based on PRs/pushes.
image

Travis will now generate monthly releases rather than nightly. Further, the existing nightly releases and tags have been deleted.
image

Github actions will handle CI, based on Roang-zero1's work: [factorio-mod-luacheck](https://github.com/Roang-zero1/factorio-mod-luacheck)

NB. The changes to travis.yml are sloppy. I changed as little as possible so that I don't have to worry about breaking anything.

### CODE REVIEW

**Comment by Claude477** [comment]
All checks have failed because main has some bug/fixed todo. https://github.com/Refactorio/RedMew/pull/1067 need do fix frist then all ohters checks are completed.

**Comment by Claude477** [comment]
https://travis-ci.org/github/Refactorio/RedMew/builds/708008902 was last when travis passed that patch fixes.

**Comment by grilledham** [comment]
Nice work.

Question: Is the plan to fix the linting issues as part of this PR, or resolve them later?

Question: Can the monthly builds be done as part of Github actions? Might be simpler to only have one system.

**Comment by Claude477** [comment]
Both working nicely but PR has bug/errors to fix them. Most them located in maze_with_rooms.lua
image

**Comment by Claude477** [comment]
PS. if that not fix any push give errors. It's like maze solving that errors list.

**Comment by Claude477** [comment]
That Check-system working better that Travis even both working same type 👍

**Comment by mheguy** [comment]
`map_gen/maps/diggy/feature/diggy_cave_collapse.lua:291:74: (W113) accessing undefined variable player_index`
I'm electing to ignore this warning because I consider diggy a black box, and I would rather leave it running with a documented but ignored linting error than to poke around and potentially cause issues with the map itself.

`map_gen/maps/diggy/feature/simple_room_generator.lua:16:7: (W211) unused variable on_entity_died`
It's unused, I'm comfortable removing the line.

---

`map_gen/maps/maze_with_rooms.lua:30:1: (W111) setting non-standard global variable value`
Made local and renamed to `exp_value`

`map_gen/maps/maze_with_rooms.lua:182:9: (W213) unused loop variable attempt`
Changed `attempt` to `_`

`map_gen/maps/maze_with_rooms.lua:484:7: (W411) variable factorio_map was previously defined on line 423`
Changed from defining to setting variable.

`map_gen/maps/maze_with_rooms.lua: - multiple unused variables and functions`
Deleted except for:
`map_gen/maps/maze_with_rooms.lua:126:16: (W211) unused function print_map`
This one I moved into the comment which has a call to the function.

`map_gen/maps/maze_with_rooms.lua: - multiple shadowed upvalues`
Ignored except for:
`map_gen/maps/maze_with_rooms.lua:85:23: (W431) shadowing upvalue b on line 4`
Renamed to `num_b` (and `a` renamed to `num_a`)


Re: #1067. It would be great to fix the linting errors rather than ignore them, but you have to be very careful in how you fix them.

Re: Using github actions to build the releases: I would like that very much. I'm just not sure how yet. =)

**Review by grilledham — APPROVED** [review]
LGTM.
I've let BlueRock know about the diggy linting warning.

**Comment by Claude477** [comment]
Good job =)

**Comment by Claude477** [comment]
LGTM.

**Pull request merged**
