### PR TITLE
Update manhattan.lua

### PR DESCRIPTION
**Pull request by Claude477**
-changed spawn point to center
-scaled map 2 to 1(easier handle monsters)
-normaly take 70hours complete map

### CODE REVIEW

**Review by grilledham — COMMENTED** [review]
If we are making the map smaller and moving the spawn to the center then I think we can reduce `grid_number_of_blocks` and `mini_grid_number_of_blocks`. Just have to check the whole map is covered in outposts after reducing the numbers.

I think we should wait for Tigress or other regular players of crashsite to confirm the new settings are better before merging.

**Comment by Claude477** [comment]
Yes, i was thinking same 👍

**Comment by Claude477** [comment]
20% smaller map and location changed. as Noted

**Comment by Claude477** [comment]
40% smaller map. as Noted

**Comment by Claude477** [comment]
reduce grid_number_of_blocks and mini_grid_number_of_blocks about 50%~

**Comment by grilledham** [comment]
The outpost number of blocks have to odd else spawn doesn't work.
image
So I fixed that.

**Pull request merged**
