### PR TITLE
Diggy-map patch

### PR DESCRIPTION
**Pull request by Claude477**
Diggy-map patch by BlueRock

### CODE REVIEW

**Comment by BlueRock2** [comment]
Description:   In Factorio 0.18 particles are now handled using LuaSurface::create_particle() instead of create_entity.   This PR is to make the needed changes to update Diggy.    Was seeing various issues with current Diggy code in 0.18.  Not only were particles not displaying, but it was also causing unexpected issues such as inconsistent ceiling collapses, biters not spawning from individual rocks (only from caves) and bot mining not working.

**Comment by Claude477** [comment]
yup this is working need w8 for merge it in server

**Review by SimonFlapse — APPROVED** [review]
LGTM. I understand it has been tested.

**Comment by Claude477** [comment]
Yup this even running in S6-server allready to go.

**Comment by BlueRock2** [comment]
Merged hail hydra particle fix (PR 1035) with this PR since all of the updates are related to the particle changes in Factorio 0.18.   Tested hail hydra update yesterday by setting debug and cheat mode to true, set evolution to 100%, and ran /c game.player.force.research_all_technologies() for weapon damage upgrades.  Verified blood explosions occurred on alien death (which is a larger effect than normal alien damage particles).   Also verified additional aliens randomly spawn on death as expected with hail hydra.

**Comment by Claude477** [comment]
all checked out ready to merge =)

**Review by grilledham — APPROVED** [review]

**Pull request merged**
