### PR TITLE
Added /find command to act the same as find_player

### PR DESCRIPTION
**Pull request by Jayefuu**
/find isn't used for anything else and /find-player takes longer to type when looking for a player who's being accused of griefing. This will shorten the time and be more intuitive. Left in /find-player so that people who are used to it can still use it.

### CODE REVIEW

**Review by mheguy — COMMENTED** [review]
I think changing from /find-player to /find makes sense.
We spoke on discord and you mentioned that you'll modify this PR before merging so will wait on that before moving forward.

**Comment by SimonFlapse** [comment]
I agree on the renaming of /find-player to only /find

**Review by Valansch — CHANGES_REQUESTED** [review]
Remove find-player

**Comment by Jayefuu** [comment]
No problem. I will make changes that will print a warning that /find-player is deprecated and will be removed in January 2019.

**Review by mheguy — COMMENTED** [review]
Wish you could delete these reviews. -_-

**Review by mheguy — CHANGES_REQUESTED** [review]
In find_player, need to check for player before calling player.print

**Comment by mheguy** [comment]
Will commit against this to tighten it up and resolve the case of `/regular demote`

**Review by Valansch — APPROVED** [review]

**Comment by Valansch** [comment]
Looking good.

**Pull request merged**
