### PR TITLE
Added biter_lane_wars PVP files. Work in progress.

### PR DESCRIPTION
**Pull request by Jayefuu**
Read the info.lua for the planned game mode.
Read the comments at the top of biter_lane_wars for how you can help and what needs doing.

- [ ] Game start GUI
- [ ] Setup teams
- [ ] Write market management code
- [ ] Set each force spawn point and enemy force spawn point
- [ ] Write a score board
- [ ] Write a starting GUI
- [ ] Set teams to spectators if more than 2 teams and 1 lose
- [ ] Add auto reset on game win condition

### CODE REVIEW

**Comment by Valansch** [comment]
I ninja edited your comment (3 times) :)

**Comment by mheguy** [comment]
Same Val, you're welcome. :p

**Comment by Valansch** [comment]
Thanks plague, you're the best!

**Comment by mheguy** [comment]
No problem buddy!

**Pull request closed without merging**
