### PR TITLE
Spidertron artillery collision fix

### PR DESCRIPTION
**Pull request by Jayefuu**
Adapted code from Damageable spider leg mod and added it to events.lua. 

Spidertrons now take damage from enemy artillery since before they were immune.

### CODE REVIEW

**Comment by Jayefuu** [comment]
Could do with discussing the failed checks before I fix them @grilledham.

**Review by grilledham — COMMENTED** [review]
As discussed I think we will need to use a different solution rather than using the `on_entity_damaged` event.

With regards to the luacheck:
 - `accessing undefined field register_on_entity_destroyed of global script`
We would need to add the event name to <https://github.com/Refactorio/RedMew/blob/develop/.luacheckrc#L1004>
 -  `value assigned to variable unit_number is unused`
Seems like a code style choice we have made to not explicitly assign to null if that value isn't used (In lua values are by default nil anyway).
 - `unused variable damageable_spider_leg` 
The local value `damageable_spider_leg` line 457 doesn't seem to be used, maybe you didn't mean to use `global.damageable_spider_leg` everywhere. Adding `damageable_spider_leg` to `Global.register` on line 22 would probably make more sense.

**Comment by Jayefuu** [comment]
The problem is that spidertrons don't have a collision mask for their bodies and so take no damage from artillery which hits the surface not the spidertron, I think.

I also spent some time looking for an event for when turrets fire or something, if I could hook into that I could remove the projectile when targetting spidertrons and replace it with a laser or something. Or directly apply damage to the spidertron when it's targetted.

I could maybe write a function that creates a laser projectile from an empty artillery turret to target entities within a range. If it just ran every 5 seconds and only targetted spidertrons it could be an interesting "new weapon" without having to use mods.

**Comment by Jayefuu** [comment]
Another idea I had was to make the spidertron non-mineable. At the moment, since it's invulnerable to artillery players just ignore the arty while in the spidertron. But if their spider goes back to base the artillery continues to fire on them even though they should be out of range. This has lead to a meta where if you return to base with your spidertron you HAVE to pick it up otherwise the arty destroys the base. By making it non-mineable players will have to park their spider somewhere it won't damage the base and somewhat offset the fact they're invulnterable to arty.,

**Comment by grilledham** [comment]
Wait, artillery targets spidertrons? I thought artillery didn't target non structure types. Has this been changed, i.e. in vanilla factorio does artillery target cars/ tanks, players, etc?

Crashsite has some special code to fake artillery targeting players and vehicles, maybe we could hook into that and do something for spidertrons 
<https://github.com/Refactorio/RedMew/blob/develop/map_gen/maps/crash_site/outpost_builder.lua#L1112>

**Comment by Jayefuu** [comment]
It definitely targets spidertrons. I'll take a look at that code, cheers.

**Comment by Jayefuu** [comment]
@grilledham I was told today that we're missing a trick with this. Apparently if we use event filters we can stop the event triggering and make it more performant than entering the event every time an entity is damaged then returning if not spidertron leg.

Please can you advise me how to add this? https://lua-api.factorio.com/latest/Event-Filters.html
And how I can test the performance.

I don't understand how it will interact with the changes you made to events within the scenario.
`script.set_event_filter(defines.events.on_entity_damaged, {{filter = "name", name = "spidertron-leg"}})`

**Comment by Jayefuu** [comment]
Closing in favour of a more performant solution, PR #1113

**Pull request closed without merging**
