### PR TITLE
Create venice.lua

### PR DESCRIPTION
**Pull request by Claude477**
Crashsite with venice.lua map

### CODE REVIEW

**Comment by Claude477** [comment]
local scale = 1
local height = 4000 * scale
local width = 4000 * scale

sizes was original
height = 2903,
width = 3833,

**Comment by theorangeangle** [comment]
@grilledham should we make a subfolder for all the crash site variants?

**Comment by grilledham** [comment]
Assuming you are talking about the files directly in the maps folder*, probably not. I think the intention was to have a flat list so that map_selection is simpler.

(* The core crashsite files already are in a separate folder.)

**Comment by theorangeangle** [comment]
Okay - are we good to merge then?
  

  
  
  

  
  
>

**Comment by grilledham** [comment]
I think I still need to check this.
I might also make a change to crashsite scenario that makes it easier to make these variants without inadvertently adding hard to spot errors.

**Pull request closed without merging**
