### PR TITLE
Find and replace 'in ipairs(' with 'in pairs('

### PR DESCRIPTION
**Pull request by mheguy**

### CODE REVIEW

**Comment by Valansch** [comment]
So many ipairs. Any non-factorio-lua dev will think you are crazy :D

**Comment by plague006** [comment]
lol is true

**Comment by grilledham** [comment]
This makes it harder to reason about if the table is an array or not. And the difference in performance between `pairs` and `ipairs` is so small that on some hardware `ipairs` is faster.

Now if you want to turn `ipairs` into `for i = 1, #tbl do local value = tbl[i] end` I can get behind that.

**Comment by mheguy** [comment]
The performance of `ipairs()` and actually a fair bit faster than `pairs()` on my PC..

**Pull request closed without merging**
