### PR TITLE
sc command

### LINKED ISSUE #56: add /savecommand /sc
local func = loadstring(str) if func then local status,error = pcall(func) if not status then game.player.print(error) end else game.player.print("Parse Error.") end

### PR DESCRIPTION
**Pull request by grilledham**
closes #56

On server 6 as `quite_command_test-deflated.zip` if anyone wants to test it

### CODE REVIEW

**Review by mheguy — COMMENTED** [review]
Works as advertised and code looks good. But can I coax you into using the new command wrapper?

**Comment by grilledham** [comment]
Currently I don't think the Command warpper supports what I need for this command.

Here is my current attempt, I've put comments in for what I want.
```lua
Command.add(
    'sc',
    {
        description = 'silent-command',
        arguments = {'str'},
        admin_only = true,
        capture_excess_arguments = true,
        allowed_by_server = true,
        allowed_by_player = true
    },
    function(args)
        local func, err = loadstring(args.str)
        if not func then
            error(err) -- I want to print err to the player or server
        end

        local _, err2 = pcall(func)
        if err2 then
            local i = err2:find('\n')
            error(err2:sub(1, i))  -- I want to print err to the player or server
        end
    end
)
```
Maybe for the command wrapper if player is nil we could mock it with 
```lua
player = {valid = true, admin = true, index = 0, print = _G.print}
```
@iltar 

edit:
Thinking about it again I think I can do what I want in the command.
```lua
Command.add(
    'sc',
    {
        description = 'silent-command',
        arguments = {'str'},
        admin_only = true,
        capture_excess_arguments = true,
        allowed_by_server = true,
        allowed_by_player = true
    },
    function(args, player)
        local p
        if player then
            p = player.print
        else
            p = print
        end

        local func, err = loadstring(args.str)
        if not func then
            p(err)
        end

        local _, err2 = pcall(func)
        if err2 then
            local i = err2:find('\n')
            p(err2:sub(1, i))
        end
    end
)
```

**Comment by linaori** [comment]
@grilledham your scenario is something I've considered building, but as Lua doesn't have actual types, mocking a LuaPlayer with a normal table can break a lot as people will assume it's a player object.

The edit you made should indeed work

**Review by Valansch — APPROVED** [review]

**Comment by mheguy** [comment]
Code looks good, works well. Merging with my thanks.

**Pull request merged**
