### PR TITLE
Add quick bar saving

### LINKED ISSUE #822: Add save/load Action Bar
Currently Action bars / Toolbars are saved on a per map basis. According to rseding we should be able to scan and set action bars with LUA. 

Ideally a player can set-up their action bar, use the save command, and have that action bar any time they join a Redmew scenario automatically.

### PR DESCRIPTION
**Pull request by mheguy**
Restores quick bars between maps automatically.

Saves or removes quick bar storage via commands.

Only registers the event hook if the server is (or was ever) present.

Closes #822

### CODE REVIEW

**Comment by mheguy** [comment]
RB+FP for merge conflicts

**Comment by mheguy** [comment]
RB+FP for merge conflicts

**Comment by mheguy** [comment]
~~Will have to iterate on this to account for missing items/mod items, and the like~~

**Comment by mheguy** [comment]
Updated to account for gaps in the saved bars as well as invalid items.

Items are checked against `game.item_prototypes` entries for validity. In cases of non-valid entries the setting of the bar entry is skipped and a player-printed message is sent.

**Comment by plague006** [comment]
Hmm.. I want to expand this to have multiple save slots.

**Comment by plague006** [comment]
Restructured a bit, cleaned up locale.
The clear bars command is currently set to debug only because I don't know if it's a good idea or not but wanted to push forward with what I had to finish this PR.

**Pull request merged**
