### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by Claude477**
This  ignore warnings only showing errors.

### CODE REVIEW

**Comment by Claude477** [comment]
https://travis-ci.org/github/Refactorio/RedMew/jobs/705003518 
ok cache completed next pulls is faster now :D
more info at https://docs.travis-ci.com/user/caching/

**Comment by grilledham** [comment]
LGTM 👍

**Comment by Claude477** [comment]
https://github.com/nickstenning/travis-pip-cache even has working travis O_O

**Comment by Claude477** [comment]
Need check out Travis cache files what they hold O_O

**Pull request closed without merging**
