### PR TITLE
Update info.lua

### PR DESCRIPTION
**Pull request by theorangeangle**
take 2

removed the BTC link and replaced with patreon, and replaced a couple of words with synonyms.

### CODE REVIEW

**Comment by grilledham** [comment]
I approve the changes.

Just quickly before this is merged:
 - who does `paypal.me/jsuesse` go to?
 - the `redmew.com/patreon`  link appears to be broken?

**Comment by Valansch** [comment]
jsuesse is diffie. Also why do hookers have to go? First you take the title puns then you take the hookers? o.O

**Comment by theorangeangle** [comment]
I want the title puns!

Just a little worried about the hookers because a guy PMed me once asking if we legit "got together once a year and had a party"

**Comment by Valansch** [comment]
>Just a little worried about the hookers part because a guy PMed me once asking if we legit "got together once a year and had a party"

Thats hilarious. But i dont see why that would motivate to remove the line :D

**Comment by theorangeangle** [comment]
got it - changed it back to hookers
(definitely didn't take 3 tries because i'm still new to this github thing)

**Pull request merged**
