### PR TITLE
Change how rotten_apples checks for military techs

### PR DESCRIPTION
**Pull request by mheguy**

### CODE REVIEW

**Comment by SimonFlapse** [comment]
It only looks for certain types of military sciences now, not all of them? You could check if a science is using military science packs. and `military`, `military-2` and `stone-walls`.

**Comment by mheguy** [comment]
Yes it only takes techs that give damage boosts. Honestly the whole map might need a rethink since, even without my changes, there are significantly less techs in the "military" category.

@Jayefuu do you have the time to rebalance/figure out a new balance?

**Comment by mheguy** [comment]
Nobody seems to want to fix this in a meaningful way right now so rather than break this in a different way I'll just leave it broken. :D

**Comment by mheguy** [comment]
Or maybe I'll just derpily hit "merge" and have to revert it.

**Pull request merged**
