### PR TITLE
Add day/night cycle options

### PR DESCRIPTION
**Pull request by plague006**
I haven't looked at this in a while and it might be a mess, but if I don't PR it now I'm likely to just forget about this branch.

### CODE REVIEW

**Comment by iltar** [comment]
Could probably just merge this and expand on it at a later point

**Comment by Valansch** [comment]
If you change the filename to README.md instead of txt github will show it if you navigate to the folder.

**Comment by plague006** [comment]
Quite right

**Comment by Valansch** [comment]
Alrighty :D

**Pull request merged**
