### PR TITLE
[Map] Rock solid

### PR DESCRIPTION
**Pull request by mheguy**
The theme of the map is no underground belts or pipes.
For balance, logistics systems research is disabled.

It's a treeless world of refined concrete underpinned by "obsidian" (dark-lab). Rail and wood are provided at a low cost in the market.

To add extra challenge to the map, cliff generation is turned up.

My hope is unruly spaghetti with splitters essentially playing the role of underground belts. Pipes will be a sweet disaster.

### CODE REVIEW

**Comment by linaori** [comment]
assemblers will be the new underground pipes

**Comment by grilledham** [comment]
https://github.com/Refactorio/RedMew/blob/835910c385ec0fba72572eb52ec3150380486ebf/utils/recipe_locker.lua#L32
The recipe unlocker registers the same event twice.

The code looks good, haven't tested it though. 

The concept makes me scream in my sleep.

**Comment by mheguy** [comment]
I submitted the PR and 3 mins later force-pushed the fix for the rebase error (the duplicate on_init function). Still too slow before both of you got to it and saw it. Fucking beasts. :D

**Comment by mheguy** [comment]
RB + FP

**Comment by mheguy** [comment]
This seems to run fine in 17 as both a concept and technically.

**Pull request merged**
