### PR TITLE
Fixed typo in peaceful_mode_on setting

### PR DESCRIPTION
**Pull request by EssGeeEich**
Fixed typo for peaceful_mode_on that accidentally turned it off.

### CODE REVIEW

**Comment by Valansch** [comment]
This is not a typo! We want our default map settings to have peaceful mode turned off.

**Comment by plague006** [comment]
Val is right that it’s not a typo.
These settings were dumped directly from the game and are the output from having all options set to default.

For more clarity: peaceful mode means biters will not attack players until players attack them, this is not the default. 

I’m closing this, but invite you to comment further if you have any questions, concerns, or uncertainties.

**Comment by mheguy** [comment]
Val is incorrect. This is a typo. This is not the default table, it’s an option that is in place to specifically enable peaceful mode. My apologies if you read my earlier comment as I didn’t properly review the contents of your changes.

**Comment by EssGeeEich** [comment]
👍

**Pull request merged**
